### ISSUE TITLE
Mac security apps

### ISSUE THREAD

**Issue by michenriksen** [mubix/sectaskbars#3]
![littlesnitch](https://user-images.githubusercontent.com/304361/44925853-d7d6cb80-ad4f-11e8-9413-be4a5d19697c.png) [Little Snitch firewall](https://www.obdev.at/products/littlesnitch/index.html)

![lulu](https://user-images.githubusercontent.com/304361/44926191-f12c4780-ad50-11e8-8448-6da6d0bc4718.png) [LuLu firewall](https://objective-see.com/products/lulu.html)

![microsnitch](https://user-images.githubusercontent.com/304361/44925887-f1781300-ad4f-11e8-8e66-09cf21c1d22a.png) [Micro Snitch microphone and webcam monitor](https://obdev.at/products/microsnitch/index.html)

![oversight](https://user-images.githubusercontent.com/304361/44925926-0f457800-ad50-11e8-8f4c-039c0f7116e6.png) [OverSight microphone and webcam monitor](https://objective-see.com/products/oversight.html)

![blockblock](https://user-images.githubusercontent.com/304361/44925955-31d79100-ad50-11e8-9238-f235dc8bac7f.png) [BlockBlock malware persistence monitor](https://objective-see.com/products/blockblock.html)

**Comment by kkirsche** [comment]
Below is the image of Little Snitch firewall when the network filter is disabled:
<img width="35" alt="screen-shot-2018-08-31-at-14 04 59" src="https://user-images.githubusercontent.com/947110/44928773-e65cbd00-ad26-11e8-9b26-84fc8e8e49c3.png">

**Comment by gerrenmurphy** [comment]
Viscosity VPN (connected): <img width="29" alt="viscosity_vpn_connected" src="https://user-images.githubusercontent.com/10334435/44949021-fe9c0d00-adf6-11e8-9c42-63c7cceb2c4d.png">
Viscosity VPN (disconnected): <img width="28" alt="viscosity_vpn_disconnected" src="https://user-images.githubusercontent.com/10334435/44949022-fe9c0d00-adf6-11e8-84da-8c874289ff11.png">
Tresorit: <img width="30" alt="tresorit_backup" src="https://user-images.githubusercontent.com/10334435/44949023-fe9c0d00-adf6-11e8-81a7-21a290744028.png">
Keepass XC: <img width="26" alt="keepass_xc" src="https://user-images.githubusercontent.com/10334435/44949024-fe9c0d00-adf6-11e8-9ce1-49ca5591ffa2.png">
